name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install dev dependencies
        run: uv sync --dev --frozen --quiet

      - name: pytest
        run: uv run pytest
