---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
      - id: ruff-check

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.51
    hooks:
      - id: ty
        name: ty orchestration
        args: [--directory, orchestration]
        files: ^orchestration/
      - id: ty
        name: ty pis
        args: [--directory, pis]
        files: ^pis/
      - id: ty
        name: ty pts
        args: [--directory, pts]
        files: ^pts/
      - id: ty
        name: ty croissant
        args: [--directory, croissant]
        files: ^croissant/

  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        args: [-conf, '.yamlfmt']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: pretty-format-json
        files: ^croissant/src/
