"""Schema for the evidence dataset.

Field order is load-bearing, not cosmetic: this dict's key order becomes the frame's column
order in `_harmonise_to_schema`, and column order feeds the content hash that decides which row
survives de-duplication in `Evidence.validate_uniqueness`. Reordering these keys silently changes
which duplicate wins. Generated from the spark `evidence.json` this replaced, preserving that
file's field order exactly.
"""

from typing import Any

import polars as pl

# `dict[str, Any]`, not `dict[str, pl.DataType]`: the values are a mix of dtype CLASSES
# (`pl.String`) and INSTANCES (`pl.List(...)`), which is what polars' own schema arguments accept
# and what the `evidence.json` loader this replaced already returned.
evidence_schema: dict[str, Any] = {
    'id': pl.String,
    'targetFromSourceId': pl.String,
    'diseaseFromSourceMappedId': pl.String,
    'actionType': pl.String,
    'biomarkerName': pl.String,
    'biomarkers': pl.Struct([
        pl.Field('geneExpression', pl.List(pl.Struct([
            pl.Field('id', pl.String),
            pl.Field('name', pl.String),
        ]))),
        pl.Field('geneticVariation', pl.List(pl.Struct([
            pl.Field('functionalConsequenceId', pl.String),
            pl.Field('id', pl.String),
            pl.Field('name', pl.String),
        ]))),
    ]),
    'confidence': pl.String,
    'datasourceId': pl.String,
    'datatypeId': pl.String,
    'diseaseFromSource': pl.String,
    'drugFromSource': pl.String,
    'drugId': pl.String,
    'drugResponse': pl.String,
    'literature': pl.List(pl.String),
    'urls': pl.List(pl.Struct([
        pl.Field('niceName', pl.String),
        pl.Field('url', pl.String),
    ])),
    'qualityControls': pl.List(pl.String),
    'diseaseId': pl.String,
    'targetId': pl.String,
    'curationDate': pl.String,
    'publicationDate': pl.String,
    'evidenceDate': pl.String,
    'score': pl.Float64,
    'diseaseFromSourceId': pl.String,
    'mutatedSamples': pl.List(pl.Struct([
        pl.Field('functionalConsequenceId', pl.String),
        pl.Field('numberMutatedSamples', pl.Int64),
        pl.Field('numberSamplesTested', pl.Int64),
        pl.Field('numberSamplesWithMutationType', pl.Int64),
    ])),
    'resourceScore': pl.Float64,
    'studyId': pl.String,
    'directionOnTrait': pl.String,
    'directionOnTarget': pl.String,
    'clinicalReportId': pl.String,
    'clinicalStage': pl.String,
    'cohortPhenotypes': pl.List(pl.String),
    'studyStartDate': pl.String,
    'trialWhyStopped': pl.String,
    'trialStopReasonCategories': pl.List(pl.String),
    'targetFromSource': pl.String,
    'allelicRequirements': pl.List(pl.String),
    'releaseDate': pl.String,
    'diseaseCellLines': pl.List(pl.Struct([
        pl.Field('id', pl.String),
        pl.Field('name', pl.String),
        pl.Field('tissue', pl.String),
        pl.Field('tissueId', pl.String),
    ])),
    'cellType': pl.String,
    'contrast': pl.String,
    'crisprScreenLibrary': pl.String,
    'geneticBackground': pl.String,
    'log2FoldChangeValue': pl.Float64,
    'projectId': pl.String,
    'statisticalTestTail': pl.String,
    'studyOverview': pl.String,
    'biomarkerList': pl.List(pl.Struct([
        pl.Field('description', pl.String),
        pl.Field('name', pl.String),
    ])),
    'geneInteractionType': pl.String,
    'geneticInteractionPValue': pl.Float64,
    'geneticInteractionScore': pl.Float64,
    'interactingTargetFromSourceId': pl.String,
    'interactingTargetRole': pl.String,
    'phenotypicConsequenceFDR': pl.Float64,
    'phenotypicConsequenceLogFoldChange': pl.Float64,
    'phenotypicConsequencePValue': pl.Float64,
    'projectDescription': pl.String,
    'releaseVersion': pl.String,
    'statisticalMethod': pl.String,
    'targetRole': pl.String,
    'pmcIds': pl.List(pl.String),
    'publicationYear': pl.Int64,
    'textMiningSentences': pl.List(pl.Struct([
        pl.Field('dEnd', pl.Int64),
        pl.Field('dStart', pl.Int64),
        pl.Field('section', pl.String),
        pl.Field('tEnd', pl.Int64),
        pl.Field('tStart', pl.Int64),
        pl.Field('text', pl.String),
    ])),
    'alleleOrigins': pl.List(pl.String),
    'clinicalSignificances': pl.List(pl.String),
    'variantFromSourceId': pl.String,
    'variantFunctionalConsequenceId': pl.String,
    'variantHgvsId': pl.String,
    'variantId': pl.String,
    'variantRsId': pl.String,
    'biosamplesFromSource': pl.List(pl.String),
    'log2FoldChangePercentileRank': pl.Int64,
    'ancestry': pl.String,
    'ancestryId': pl.String,
    'beta': pl.Float64,
    'betaConfidenceIntervalLower': pl.Float64,
    'betaConfidenceIntervalUpper': pl.Float64,
    'cohortId': pl.String,
    'oddsRatio': pl.Float64,
    'oddsRatioConfidenceIntervalLower': pl.Float64,
    'oddsRatioConfidenceIntervalUpper': pl.Float64,
    'pValueExponent': pl.Int64,
    'pValueMantissa': pl.Float64,
    'sex': pl.List(pl.String),
    'statisticalMethodOverview': pl.String,
    'studyCases': pl.Int64,
    'studyCasesWithQualifyingVariants': pl.Int64,
    'studySampleSize': pl.Int64,
    'studyLocusId': pl.String,
    'biologicalModelAllelicComposition': pl.String,
    'biologicalModelGeneticBackground': pl.String,
    'biologicalModelId': pl.String,
    'diseaseModelAssociatedHumanPhenotypes': pl.List(pl.Struct([
        pl.Field('id', pl.String),
        pl.Field('label', pl.String),
    ])),
    'diseaseModelAssociatedModelPhenotypes': pl.List(pl.Struct([
        pl.Field('id', pl.String),
        pl.Field('label', pl.String),
    ])),
    'targetInModel': pl.String,
    'targetInModelEnsemblId': pl.String,
    'targetInModelMgiId': pl.String,
    'cohortDescription': pl.String,
    'cohortShortName': pl.String,
    'significantDriverMethods': pl.List(pl.String),
    'cellLineBackground': pl.String,
    'assays': pl.List(pl.Struct([
        pl.Field('description', pl.String),
        pl.Field('isHit', pl.Boolean),
        pl.Field('shortName', pl.String),
    ])),
    'assessments': pl.List(pl.String),
    'primaryProjectHit': pl.Boolean,
    'primaryProjectId': pl.String,
    'pathways': pl.List(pl.Struct([
        pl.Field('id', pl.String),
        pl.Field('name', pl.String),
    ])),
    'reactionId': pl.String,
    'reactionName': pl.String,
    'targetModulation': pl.String,
    'variantAminoacidDescriptions': pl.List(pl.String),
}
