---
environment_specs:
  - name: Prod
    vars:
      metadata_uri: "https://raw.githubusercontent.com/eQTL-Catalogue/eQTL-Catalogue-resources/fd99d45d3e433dcdf3c3d0acb4db0b7d5e8a7bd3/data_tables/dataset_metadata_r8.tsv"
      credible_set_glob: gs://eqtl_catalogue_processed_otar_internal_data/otar2077/eQTL_Catalogue_r8_260626/susie/QTS*/QTD*/QTD*.credible_sets.parquet
      lbf_glob: gs://eqtl_catalogue_processed_otar_internal_data/otar2077/eQTL_Catalogue_r8_260626/susie/QTS*/QTD*/QTD*.lbf_variable.parquet
      study_index_output_path: gs://eqtl_catalogue_data/r8/study_index/
      credible_set_output_path: gs://eqtl_catalogue_data/r8/credible_set
env: Prod

dataproc:
  cluster_name: otg-preprocess-eqtl
  cluster_config:
    project_id: open-targets-genetics-dev
    autoscaling_policy: eqtl-preprocess
    metadata:
      GENTROPY_REF: v3.3.0
    init_actions_uris:
      - "gs://genetics_etl_python_playground/initialisation/install_dependencies_on_cluster.sh"
    num_workers: 4
    worker_machine_type: n1-highmem-8

nodes:
  - id: eqtl_catalogue
    kind: Task
    prerequisites: []
    params:
      step: eqtl_catalogue
      step.eqtl_catalogue_dataset_metadata_path: "{metadata_uri}"
      step.credible_set_input_glob: "{credible_set_glob}"
      step.lbf_input_glob: "{lbf_glob}"
      step.study_index_output_path: "{study_index_output_path}"
      step.credible_set_output_path: "{credible_set_output_path}"
      step.lead_pvalue_threshold: 1.0e-3
      step.session.write_mode: overwrite
      step.session.output_partitions: 20
      step.mqtl_quantification_methods_blacklist: []
      +step.session.extended_spark_conf: "{spark.sql.shuffle.partitions: '1536'}"
